// Devicon CDN base URL for HD official brand icons
export const DEVICON_BASE = 'https://cdn.jsdelivr.net/gh/devicons/devicon@v2.16.0/icons';

export const IDE_THEMES = [
  { id: 'vscode-dark', label: 'VS Code Dark' },
  { id: 'dracula', label: 'Dracula' },
  { id: 'nord', label: 'Nord' },
  { id: 'tokyo-night', label: 'Tokyo Night' },
  { id: 'cyberpunk', label: 'Cyberpunk' },
  { id: 'glass-light', label: 'Glass Light' },
  { id: 'custom', label: 'Custom Creator' },
];

// Map of language IDs to their Devicon icon paths
export const DEVICON_MAP = {
  python: 'python/python-original.svg',
  python2: 'python/python-original.svg',
  tkinter: 'python/python-original.svg',
  matplotlib: 'matplotlib/matplotlib-original.svg',
  seaborn: 'python/python-original.svg',
  pygame: 'python/python-original.svg',
  turtle: 'python/python-original.svg',
  javascript: 'javascript/javascript-original.svg',
  bun: 'bun/bun-original.svg',
  typescript: 'typescript/typescript-original.svg',
  deno: 'denojs/denojs-original.svg',
  html: 'html5/html5-original.svg',
  css: 'css3/css3-original.svg',
  react: 'react/react-original.svg',
  vue: 'vuejs/vuejs-original.svg',
  angular: 'angularjs/angularjs-original.svg',
  bootstrap: 'bootstrap/bootstrap-original.svg',
  tailwindcss: 'tailwindcss/tailwindcss-original.svg',
  htmx: 'html5/html5-original.svg',
  alpinejs: 'alpinejs/alpinejs-original.svg',
  chartjs: 'chartjs/chartjs-original.svg',
  d3js: 'd3js/d3js-original.svg',
  jquery: 'jquery/jquery-original.svg',
  foundation: 'foundation/foundation-original.svg',
  bulma: 'bulma/bulma-plain.svg',
  backbonejs: 'backbonejs/backbonejs-original.svg',
  go: 'go/go-original.svg',
  rust: 'rust/rust-original.svg',
  java: 'java/java-original.svg',
  jshell: 'java/java-original.svg',
  javaswing: 'java/java-original.svg',
  javafx: 'java/java-original.svg',
  c: 'c/c-original.svg',
  cpp: 'cplusplus/cplusplus-original.svg',
  raylib: 'cplusplus/cplusplus-original.svg',
  ispc: 'c/c-original.svg',
  php: 'php/php-original.svg',
  nodejs: 'nodejs/nodejs-original.svg',
  csharp: 'csharp/csharp-original.svg',
  avalonia: 'csharp/csharp-original.svg',
  ruby: 'ruby/ruby-original.svg',
  swift: 'swift/swift-original.svg',
  kotlin: 'kotlin/kotlin-original.svg',
  bash: 'bash/bash-original.svg',
  sh: 'bash/bash-original.svg',
  shell: 'bash/bash-original.svg',
  markdown: 'markdown/markdown-original.svg',
  lua: 'lua/lua-original.svg',
  assembly: 'wasm/wasm-original.svg',
  vb: 'dot-net/dot-net-original.svg',
  pascal: 'pascal/pascal-original.svg',
  groovy: 'groovy/groovy-original.svg',
  scala: 'scala/scala-original.svg',
  prolog: 'prolog/prolog-original.svg',
  haskell: 'haskell/haskell-original.svg',
  ada: 'ada/ada-original.svg',
  lisp: 'lisp/lisp-original.svg',
  scheme: 'lisp/lisp-original.svg',
  d: 'd/d-original.svg',
  elixir: 'elixir/elixir-original.svg',
  erlang: 'erlang/erlang-original.svg',
  fsharp: 'fsharp/fsharp-original.svg',
  fortran: 'fortran/fortran-original.svg',
  perl: 'perl/perl-original.svg',
  r: 'r/r-original.svg',
  racket: 'racket/racket-original.svg',
  ocaml: 'ocaml/ocaml-original.svg',
  clojure: 'clojure/clojure-original.svg',
  cobol: 'cobol/cobol-original.svg',
  rust2: 'rust/rust-original.svg',
  objectivec: 'objectivec/objectivec-plain.svg',
  octave: 'matlab/matlab-original.svg',
  coffeescript: 'coffeescript/coffeescript-original.svg',
  dart: 'dart/dart-original.svg',
  crystal: 'crystal/crystal-original.svg',
  julia: 'julia/julia-original.svg',
  zig: 'zig/zig-original.svg',
  nim: 'nim/nim-original.svg',
  haxe: 'haxe/haxe-original.svg',
  mysql: 'mysql/mysql-original.svg',
  oracle: 'oracle/oracle-original.svg',
  plsql: 'oracle/oracle-original.svg',
  postgres: 'postgresql/postgresql-original.svg',
  questdb: 'postgresql/postgresql-original.svg',
  mongodb: 'mongodb/mongodb-original.svg',
  sqlite: 'sqlite/sqlite-original.svg',
  redis: 'redis/redis-original.svg',
  mariadb: 'mariadb/mariadb-original.svg',
  mssql: 'microsoftsqlserver/microsoftsqlserver-original.svg',
  cassandra: 'cassandra/cassandra-original.svg',
};

export const languageDictionaries = {
  javascript: [
    { label: 'console', type: 'variable' },
    { label: 'log', type: 'function' },
    { label: 'error', type: 'function' },
    { label: 'warn', type: 'function' },
    { label: 'info', type: 'function' },
    { label: 'document', type: 'variable' },
    { label: 'window', type: 'variable' },
    { label: 'setTimeout', type: 'function' },
    { label: 'setInterval', type: 'function' },
    { label: 'clearTimeout', type: 'function' },
    { label: 'clearInterval', type: 'function' },
    { label: 'Promise', type: 'class' },
    { label: 'JSON', type: 'class' },
    { label: 'Math', type: 'class' },
    { label: 'Array', type: 'class' },
    { label: 'Object', type: 'class' },
    { label: 'String', type: 'class' },
    { label: 'Number', type: 'class' },
    { label: 'Boolean', type: 'class' },
    { label: 'Function', type: 'class' },
    { label: 'RegExp', type: 'class' },
    { label: 'Map', type: 'class' },
    { label: 'Set', type: 'class' },
    { label: 'const', type: 'keyword' },
    { label: 'let', type: 'keyword' },
    { label: 'var', type: 'keyword' },
    { label: 'function', type: 'keyword' },
    { label: 'class', type: 'keyword' },
    { label: 'return', type: 'keyword' },
    { label: 'if', type: 'keyword' },
    { label: 'else', type: 'keyword' },
    { label: 'for', type: 'keyword' },
    { label: 'while', type: 'keyword' },
    { label: 'do', type: 'keyword' },
    { label: 'switch', type: 'keyword' },
    { label: 'case', type: 'keyword' },
    { label: 'default', type: 'keyword' },
    { label: 'try', type: 'keyword' },
    { label: 'catch', type: 'keyword' },
    { label: 'finally', type: 'keyword' },
    { label: 'throw', type: 'keyword' },
    { label: 'new', type: 'keyword' },
    { label: 'typeof', type: 'keyword' },
    { label: 'instanceof', type: 'keyword' },
    { label: 'import', type: 'keyword' },
    { label: 'export', type: 'keyword' },
    { label: 'from', type: 'keyword' },
    { label: 'async', type: 'keyword' },
    { label: 'await', type: 'keyword' },
  ],
  python: [
    { label: 'print', type: 'function' },
    { label: 'len', type: 'function' },
    { label: 'range', type: 'function' },
    { label: 'str', type: 'class' },
    { label: 'int', type: 'class' },
    { label: 'float', type: 'class' },
    { label: 'list', type: 'class' },
    { label: 'dict', type: 'class' },
    { label: 'set', type: 'class' },
    { label: 'tuple', type: 'class' },
    { label: 'open', type: 'function' },
    { label: 'input', type: 'function' },
    { label: 'type', type: 'function' },
    { label: 'isinstance', type: 'function' },
    { label: 'def', type: 'keyword' },
    { label: 'class', type: 'keyword' },
    { label: 'return', type: 'keyword' },
    { label: 'if', type: 'keyword' },
    { label: 'elif', type: 'keyword' },
    { label: 'else', type: 'keyword' },
    { label: 'for', type: 'keyword' },
    { label: 'while', type: 'keyword' },
    { label: 'break', type: 'keyword' },
    { label: 'continue', type: 'keyword' },
    { label: 'import', type: 'keyword' },
    { label: 'from', type: 'keyword' },
    { label: 'as', type: 'keyword' },
    { label: 'try', type: 'keyword' },
    { label: 'except', type: 'keyword' },
    { label: 'finally', type: 'keyword' },
    { label: 'raise', type: 'keyword' },
    { label: 'assert', type: 'keyword' },
    { label: 'global', type: 'keyword' },
    { label: 'nonlocal', type: 'keyword' },
    { label: 'lambda', type: 'keyword' },
    { label: 'pass', type: 'keyword' },
    { label: 'with', type: 'keyword' },
    { label: 'yield', type: 'keyword' },
    { label: 'in', type: 'keyword' },
    { label: 'is', type: 'keyword' },
    { label: 'and', type: 'keyword' },
    { label: 'or', type: 'keyword' },
    { label: 'not', type: 'keyword' },
    { label: 'True', type: 'constant' },
    { label: 'False', type: 'constant' },
    { label: 'None', type: 'constant' },
  ],
  cpp: [
    { label: 'printf', type: 'function' },
    { label: 'scanf', type: 'function' },
    { label: 'sprintf', type: 'function' },
    { label: 'fprintf', type: 'function' },
    { label: 'malloc', type: 'function' },
    { label: 'free', type: 'function' },
    { label: 'strlen', type: 'function' },
    { label: 'strcmp', type: 'function' },
    { label: 'strcpy', type: 'function' },
    { label: 'std', type: 'namespace' },
    { label: 'cout', type: 'variable' },
    { label: 'cin', type: 'variable' },
    { label: 'endl', type: 'variable' },
    { label: 'vector', type: 'class' },
    { label: 'string', type: 'class' },
    { label: 'map', type: 'class' },
    { label: 'set', type: 'class' },
    { label: 'int', type: 'type' },
    { label: 'float', type: 'type' },
    { label: 'double', type: 'type' },
    { label: 'char', type: 'type' },
    { label: 'bool', type: 'type' },
    { label: 'void', type: 'type' },
    { label: 'const', type: 'keyword' },
    { label: 'class', type: 'keyword' },
    { label: 'struct', type: 'keyword' },
    { label: 'public', type: 'keyword' },
    { label: 'private', type: 'keyword' },
    { label: 'protected', type: 'keyword' },
    { label: 'return', type: 'keyword' },
    { label: 'if', type: 'keyword' },
    { label: 'else', type: 'keyword' },
    { label: 'for', type: 'keyword' },
    { label: 'while', type: 'keyword' },
    { label: 'do', type: 'keyword' },
    { label: 'switch', type: 'keyword' },
    { label: 'case', type: 'keyword' },
    { label: 'break', type: 'keyword' },
    { label: 'continue', type: 'keyword' },
    { label: 'new', type: 'keyword' },
    { label: 'delete', type: 'keyword' },
    { label: 'namespace', type: 'keyword' },
    { label: 'using', type: 'keyword' },
    { label: 'template', type: 'keyword' },
    { label: 'typename', type: 'keyword' },
    { label: 'virtual', type: 'keyword' },
    { label: 'override', type: 'keyword' },
  ],
  java: [
    { label: 'System', type: 'class' },
    { label: 'out', type: 'variable' },
    { label: 'print', type: 'function' },
    { label: 'println', type: 'function' },
    { label: 'printf', type: 'function' },
    { label: 'String', type: 'class' },
    { label: 'Integer', type: 'class' },
    { label: 'Double', type: 'class' },
    { label: 'Boolean', type: 'class' },
    { label: 'Math', type: 'class' },
    { label: 'Scanner', type: 'class' },
    { label: 'List', type: 'class' },
    { label: 'ArrayList', type: 'class' },
    { label: 'Map', type: 'class' },
    { label: 'HashMap', type: 'class' },
    { label: 'Set', type: 'class' },
    { label: 'HashSet', type: 'class' },
    { label: 'public', type: 'keyword' },
    { label: 'private', type: 'keyword' },
    { label: 'protected', type: 'keyword' },
    { label: 'static', type: 'keyword' },
    { label: 'final', type: 'keyword' },
    { label: 'class', type: 'keyword' },
    { label: 'interface', type: 'keyword' },
    { label: 'extends', type: 'keyword' },
    { label: 'implements', type: 'keyword' },
    { label: 'return', type: 'keyword' },
    { label: 'if', type: 'keyword' },
    { label: 'else', type: 'keyword' },
    { label: 'for', type: 'keyword' },
    { label: 'while', type: 'keyword' },
    { label: 'do', type: 'keyword' },
    { label: 'switch', type: 'keyword' },
    { label: 'case', type: 'keyword' },
    { label: 'break', type: 'keyword' },
    { label: 'continue', type: 'keyword' },
    { label: 'new', type: 'keyword' },
    { label: 'this', type: 'keyword' },
    { label: 'super', type: 'keyword' },
    { label: 'void', type: 'type' },
    { label: 'int', type: 'type' },
    { label: 'double', type: 'type' },
    { label: 'float', type: 'type' },
    { label: 'char', type: 'type' },
    { label: 'boolean', type: 'type' },
  ],
};
